# Generated by Django 4.1.3 on 2022-11-24 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proctor',
            name='author',
        ),
        migrations.RemoveField(
            model_name='proctor',
            name='phone',
        ),
        migrations.AlterField(
            model_name='proctor',
            name='email',
            field=models.EmailField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Enter a valid email address.', regex='^([a-z\\d\\.-]+)@bmsce.ac.in')]),
        ),
    ]
