# Generated by Django 4.1.3 on 2022-11-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_remove_proctor_author_remove_proctor_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proctor',
            old_name='name',
            new_name='username',
        ),
    ]
