# Generated by Django 4.1.3 on 2022-11-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_rename_name_proctor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctor',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
